> 1a2y
---EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSS--B---EEEEE----EEEEE--SEE-TTS-EEEEEEEESS-TTSSEEEEEEE-TTS--EEEEEE-TTS-EEE-TTTGGGEEEEEEGGGTEEEEEE-S--GGG-EEEEEEEESSSSEEEE---EEEEE----B--HHHHHHHHHHTT-TTBTTB-HHHHHHHHHHHHTTBTT-EEE-TTS-EEETTTTEETTTTSB-S--TT---TT-SBGGGG-SSS-HHHHHHHHHH--STTGGGG-HHHHHHTTTS-GGGGTTTS--
