> 1aoh
-EEEEE-EEEE-TT-EEEEEEEEES--TT-BSEEEEEEE--TTTEEEEEEEE-TT---SSHHHHEEEEEETTTTEEEEEEE-TTSSSTT-B-SSEEEEEEEEEE-TTPPSEEEEEEEEEEEEEE-TT-PBPPEEEE-EEEEE----TTSEEEEE-EEEE-TT-EEEEEEEEES--TT-EEEEEEEEE--TTTEEEEEEEE-TT---SSHHHHEEEEEETTTTEEEEEEE-TTSSSTT-B-SSEEEEEEEEEE-TTPPSEEEEEEEEEEEEEEETT-PBPPEEEE-EEEEE-
