> 1b88
--SEEEE-SEEEEETTEEEEEEEEE--TT--EEEEEEE-TTS--EEEEEEESS----BSSS-EEEEETTTTEEEEEEEEE-GGG-SEEEEEEES-TTTTPPEEE---EE--EE-----EEEE-SEEEEETTPPEEEEEEE--TT--B--EEEE-TTS--EEEE--BTT-SEEE-SSEEEEEETTTTEEEEEETT--GGG-SEEEEEEBS-SSS----EE---EE-EEE-
