> 1bmz
--EEEEEEETTTTEE--S-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB---EEEEEEEETTEEEEEEEE----EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB---EEEEEEEETTEEEEEEEE-
