> 1bz8
----S--SS-SEEEEEEETTTTEE--S-EEEEEEE-TTSSEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEE-SSS---EEEEEEEETTEEEEEE--SS-----B-S--SS-SEEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEEB-S--TTT--SEEEEEEE-HHHHHHHHT---SEEEEEEEEEE-TTS-S-EEEEEEEETTEEEEEE--SS--
