> 1bzd
---SSS-SS-SEEEEEEETTTTEE--S-EEEEEEEETTTEEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE-------B-S---S-SEEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEEB-S--TTT--SEEEEEEE-HHHHHHHTT---SBS-EEEEEEE-SSS-SEEEEEEEEETTEEEEEEEEESS--
