> 1c78
--S-S-SS--SSPPSS-EEEE--EEE-TTS-EEE----EEEE--TT-EE-HHHHHHHHHHHHTTSTTTTEEEEEE-TT-EEEEEEE-TTT-SEEEEEEE--SS-EEPP--TTT-SS-EEEE--EEEEEE----S-SS--SS--SS-EEEEEEEEE-TT--EEEEEEEEEEE--TT-EE-HHHHHHHHHHHHTTSTTTTEEEEEE-TT-EEEEEEEETTTTEEEEEEEE--SS-EEPPP-TTT-SS-EEEEEEEEEEEE-
