> 1dvt
--EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE----EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEE--SSS--EEEEEEEETTEEEEEEEE-
