> 1dvy
--EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE----EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEE--SSS--EEEEEEEETTEEEEEEEE-
