> 1eaj
--SS-EESSSEEEEEEETTS-EEE--BEE--TT--S-EEEEEEEEETTSS--SEEEEEEETTEEE-TTSSTTTTTEEE--S-GGGTB--EEE-S--GGG-EEEEEEEEETTEEEEEEEEEEEE---EE-SPPEEEEEETTS-EEE--BEE--TT--S-EEEEEEEEETTSS--SEEEEEEETTEEE-TTSSTTTTTEEE--S-GGGTB--EEE-S--GGG-EEEEEEEEETTEEEEEEEEEEEE-
