> 1eo6
---HHHHHS-HHHHHHHHHHHHHH-TTEEEEEEEEPTT-SSPP-S--EEEEETTSBHHHHHHHHHHHHT--TTS--EEEBTTB---TTSBHHHHHHHH--TTS-EEEEEE----------HHHHHS-HHHHHHHHHHHHHH-TTEEEEEEEEPTT-SSPPPS--EEEEETTSBHHHHHHHHHHHTT--TTS--EEEBTTB---TTSBHHHHHHHH--TTSPEEEEEESS-TT--
