> 1eta
---SSS-SS--EEEEEEETTTTEE--S----EEEE-TTS-EEEEE-----TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE--------SSSSSS-SEEEEEEETTTTEE--S----EEEE-TTS-EEEEE-----TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEE-SSS-SEEEEEEEEETTEEEEEEEEESS--
