> 1etb
--SEEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE------SEEEEEEETTTTEE--S-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEE-SSS-SEEEEEEEEETTEEEEEEEEE--
