> 1f2x
--EEEEE--EEEETT--EEEEEEEESS-TTTS-EEEEEE-TTS--EEEEEEETTEEEE-TTTTTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEE-S---HHHHHT--GGGSSEE---EEEEEE---EEEEE--EEEETT--EEEEEEEESS-TTTS-EEEEEE-TTS--EEEEEEETTEEEE-TTTTTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEE-S---HHHHTT--GGGSSEE---EEEEEE--
