> 1f5w
--SS-EESSSEEEEEEETTS-EEE--BEE--TT--S-EEEEEEEEETTSS--SEEEEEEETTEEE-TTSSTTTTTEEE--S-GGGTB--EEE-S--GGG-EEEEEEEEETTEEEEEEEEEEEE---EEE-SPPEEEEEETTS-EEE--BEEE-TT--S-EEEEEEEEETTSS--SEEEEEEETTEEE-TTSSTTTTTEEE--S-GGGTB--EEE-S--GGG-EEEEEEEEETTEEEEEEEEEEEE-
