> 1f86
--EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE----EEEEEEETTTTEE--S-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SEEEEEEEEEE--SS--EEEEEEEE-SSEEEEEEEEE-
