> 1g1k
--EEEEE-EEEE-TT-EEEEEEEEESTGGGT-BSEEEEEEE--TTTEEEEEEEE-TT-SSHHHHEEEEEETTEEEEEEE-SS-GGGSB-S-EEEEEEEEEEPP-SS-EEEEEEEEEEEEEE-TTS-B-S-EEEE-EEEEE------EEEEE-EEEE-TT-EEEEEEEEESTGGGT-BSEEEEEEE--TTTEEEEEEEE-TT-SSHHHHEEEEEETTEEEEEEE-SS-GGGSB-S-EEEEEEEEEEPP-SS-EEEEEEEEEEEEEE-TTS-B-S-EEEE-EEEEE---
