> 1hz6
----S-EEEEEEEE-TTS-EEEEEEEESHHHHHHHHHHHHHHTHHHH--EEEEEEGGGTEEEEEE-----EEEEEEEE-TTS-EEEEEEEE-HHHHHHHHHHHHHHTHHHH--EEEEEEGGGTEEEEEE-----EEEEEEEE-TTS-EEEEEEEESHHHHHHHHHHHHHHTHHHH--EEEEEEGGGTEEEEEE--
