> 1i3v
--EEEEE---EEETT--EEEEEEEESS-GGGSEEEEEEE-TTS--EEEEEEEEEEEETTEEEEEE-TTTBTTEEEEEEGGGTEEEEEE-S--GGG-EEEEEEEESSS-S-S-STT-SEE---EEEEEE----EEEEE--EEEETT--EEEEEEEESS-GGGSEEEEEEE-TTS-EEEEEEEEEEEEETTEEEEEE-TTTTTTEEEEEEGGGTEEEEEE-S--GGG-EEEEEEEES-S-S-SSGGG-SEE---EEEEEE-
