> 1ic4
---EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS--EEEEBTTTB--TTS-TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSS-EE---EEEEE----EEEEES-SEE-TTS-EEEEEEEESS--TTS-EEEEEE-TTS-EEEEEEE-TTS-EEE-GGGTT-EEEEEETTTTEEEEEE-S--GGG-EEEEEEETTSS-B---EEEEE-----B--HHHHHHHHHHTT-TTBTTB-HHHHHHHHHHHHTTBTT-EEE-TTS-EEETTTTEETTTTSB-S--TT---TT-SBGGGGSSSS-HHHHHHHHHHTTSTTGGGGSHHHHHHTTTS-GGGGGTT---
