> 1jhl
---EEEE-SEEEE-TTS-EEEEEEESS--TT-EEEEEE-TTSPPEEEEETTTEEPTT--TTEEEEESSSEEEEEE-S--TT--SEEEEEE-SSSSPEE---EEEEEP----EEEE---EE--TT--EEEEEEEESS-GGGS-EEEEEE-TTS-EEEEEEEETTTTEEEE-TTTTTTEEEEEETTTTEEEEEESS--GGG-EEEEEEEE-SSSSEEEE---EEEE---B--HHHHHHHHHHTT-TTBTTB-HHHHHHHHHHHTSSBTT-EEE-TTS-EEETTTTEETTTT-B-SS-TT---TT-SBGGGGGSSSTHHHHHHHHHHHTSTTGGGGSHHHHHHTTTS-GGGGTTT---
