> 1k26
-EEEEEE-EETTEEEEEE-TTT-SEE-SEEEPPTTS-HHHHHHHHHHHHHSEEEEEE------BSSSEEE-PPPSEEEEEEEE-SS-EEEEEEEEEEEEEEEE---S-EEEEGGGGGGS-BSTTHHHHHHHHHHHHHHHHHHHHHHHH----EEEEEE-EETTEEEEEE-TTT-SEE-SEEEPPTTS-HHHHHHHHHHHHHSEEEEEE------EETTEEE-PPPSEEEEEEEE-SS-EEEEEEEEEEEEEEEE---S-EEEETT-GGGS-B-TTHHHHHHHHHHHHHHTTSS-TTT-
