> 1kmt
-BPPSEEEEEEEEE-TTSSS--EEETTS-GGGGGG--EEEETT-EEEEEEEEEE-SS-EEEEEEEEEEEETTEEEEEEEEEEEEE---SSPEEEEPPPEE---STTT-EEEEEEEEEE-TT---SEEEEEEEEEES----PPPSEEEEEEEEE-TT-SS--EEETTS-GGGGGG--EEEETT-EEEEEEEEEE-SS-EEEEEEEEEEEETTEEEEEEEEEEEEE---SSPEEEEPPPEE---SGGG-EEEEEEEEEE-TT---SEEEEEEEEEES--
