> 1lm8
-EEEEEEEEBTEEEEEEEETTSBHHHHHHHHHHHH---GGGEEEEETTEEPPTTSBTTTTT--TTTSBTTBPEEEEEEE--SSS-----B-------PPPGGGS----EEEEE-TTS-EEEEEHHHHTTSHHHHHHT-----EEE-TTS-HHHHHHHHHHHHHHHHHTT--SPPPP----GGGHHHHHHHHHHHT----SS-------EEEEEEEE-SSSPEEEEEE-TTS-EEE---B-TTEEEEEEEETT-EEEEEETTT--B-EETTBS-B---PPBTTBPEEEEEE-----HHHHHHHHHHHHS-GGGGGGS-S-HHHHHHHHS---HHHHHHHHHHHHHS----------S---EE--
