> 1lqb
-EEEEEEEEBTEEEEEEEETTSBHHHHHHHHHHHH---GGGEEEEETTEEPPTTSBTTTTT--TTTSBTTBPEEEEEEE--SS------B-------PPPGGG---EEEEE-TTS-EEEEEHHHHTTSHHHHHHT-----EEE-TTS-HHHHHHHHHHHHHHHHHTT--SPPPP----GGGHHHHHHHHHHHT----S-------EEEEEEEE-SSS-EEEEEE-TTS-EEE---B-TTEEEEEEEETT-EEEEEETTT--B-EETTBS-B-----SSS-PEEEEEE-----HHHHHHHHHHHHS-GGGGGGS-S-THHHHHHHS---HHHHHHHHHHHHHHTT--------------EE-TT-
