> 1mff
-EEEEEESS-GGGSPTTHHHHHHHHHHHHHT--GGG-EEEEE-S-EEEETTB-SS-EEEEEEESS--SHHHHHHHHHHHHHHHHHHH---GGGEEEEEEE--GGGEEETTEE----EEEEEESS-GGGS-TTHHHHHHHHHHHHH---GGG-EEEEE-S-EEEETTB-SS-EEEEEEESS---HHHHHHHHHHHHHHHHHHH---GGGEEEEEEE--GGGEEETTEE----EEEEEESS-GGGS-TTHHHHHHHHHHHHHT--GGG-EEEEE-S-EEEETTB-SS-EEEEEEESS--SHHHHHHHHHHHHHHHHHHH---GGGEEEEEEE--GGGEEETTEE--
