> 1mvf
-EEEEEE--EEEETT--EEEEEEEEESGGG--EEEEEEE-TTSPPEEEEEEETTT--EEE-TTTBTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEEESS--SS-TTSGGG-SEE---EEEEEE---EEEE--EEE-TT--EEEEEEE-------EEEEEEE-SS---EEEEEEETTTTEEEE-TTTTTTEEEEE-SSSSEEEEEE-S--GGG-EEEEEEEESS--SS-TTSGGG-SEE---EEEEE---B-EEETTEEEEE--HHHHHHTT--TT-BEEEEEETTEEEEEE---B-EESSSSEEEE--HHHHHHTT--TT-BEEEEEETTEEEEEE-
