> 1nme
-------B----SSEEEEEEEEE-----GGGTPPP-TTHHHHHHHHHHHHHHTT-EEEEEES--HHHHHHHHHHHHTS--TTEEEEEEEEES-EETTEEEETTEEEEHHHHHHTTSTTT-GGGTTS-EEEEEES-SSSB-B---------TTTTEEEEESS-TTB---EETTTEEHHHHHHHHHHHHHTTTS-HHHHHHHHHHHHHHH-----SSGGGTT-B---EEEE--SSB--S--
