> 1nvi
-EEEEE-HHHHHHHT-SEEEE-S--SBHHHHHHHHHTT-HHHHHHH--SS-EEEETTEE--TT-B--TT-EEEEEPPP------EEEEEESS---HHHHHHHHH--TT--EEEEEEEE------EEEEE-TTHHHHHHHHHHHHHHHHS-EEEEEEEEE-EEE-TT-EEEEEEEEESSHHHHHHHHHHHHHHHHHHS-EEEEE-TTTS-EEPPP-HHHHHHHHT-
