> 1oaq
--EEEE---EEE-TT--EEEEEEEESS-GGGEEEEEEEE-TTS-EEEEEEE-TTT--EEE-GGGTTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEEEETTS---EEEE---EEEEE------EEE-SEEEE-TT-EEEEEEEETTB---GGG--EEEEEETTTEEEEEEETTTEEPTTS-TTEEEEEETTEEEEEEES--GGG-EEEEEEEEETTEEEE---EEEEE--
