> 1qp1
---EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSSPEE---EEEEE---PPEEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-SEEEEEE-SSSSPEE---EEEEE-----EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSSPEE---EEEEE-
