> 1tfp
--EEEEEEETTTTEEPPS-EEEEEEE-TTS-EEEEEEEE--TTS--S-SS-TTT--SEEEEEEEE-TTTTGGGT--TT--EEEEEEEE-SSS---EEEEEEE-SSEEEEEEEE----EEEEEEETTTTEEPPS-EEEEEEE-TTS-EEEEEEEE--TTS--S-SS-TTTS-SEEEEEEEE-SSTTTTTT-----EEEEEEEEETSSS---EEEEEEE-SSEEEEEEEE-
