> 1ttc
---SSS-SS--EEEEEEETTTTEE--S-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEE-BTB--EEEEEEEEETTEEEEEEEEE-S------SSSS-S-SEEEEEEETTTTEE--S-EEEEEEE-TTSSEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SBS-EEEEEEE-TTSS-EEEEEEEEETTEEEEEEEEE-S--
