> 1tvd
-EEE--SPPEEEETT--EEE--EEE--SSS--EEEEEE-TTS-EEEEEEE-SS-EEE-GGGTTTEEEEEEGGGTEEEEEESS--GGG-EEEEEEEEPTTTT--EEE---EEEEEE---EEE--PPPEEEETT--EEE--EEE-SSSS--EEEEEE-TTS-EEEEEEE-SS-EEE-GGGTTTEEEEEEGGGTEEEEEESS--GGG-EEEEEEEEPPTTT--EEE---EEEEEE-
