> 1tyr
---SSS-SS-SEEEEEEETTTTEE-TT-EEEEEEE-TTSSEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE--------SS--SS-SEEEEEEETTTTEE--S-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHHT---SBS-EEEEEEE-SSS-SEEEEEEEEETTEEEEEEEEESS--
