> 1ves
-EEEEE-SEEEE-TT--EEEEEEEES-SS---EEEEEEEETT----EEPPPBTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEEEEEE--SSTT--EEEEEEE---EEEEE---EEEEE-SEEEE-TT--EEEEEEEES-SSPP-EEEEEEEETT----EE---BTTEEEEEETTTTEEEEEE-S--GGG-EEEEEEEEEEE--S-SS--EEEEEEE---EEEEE-
