> 1wtl
---EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTS-EEEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSSPEE---EEEEE------EEEE-SEEEE-TT--EEEEEEESS--TT-EEEEEE-TTSPPEEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSS--B---EEEEE--
