> 2dlf
-PPEEEE-SEEEE-TT--EEEEEEESS--B-TTS-B-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEE-S--GGG-EEEEEEE-SSSSPEE---EEEEE-----EEEEE---EE-TT--EEEEEEEESS-GGG-EEEEEEEETTTEEEEEEEE--GGGTT-EEE-TTTTTTEEEEEEGGGTEEEEEE-S--GGG-EEEEEEEE-SSS-SB------EEEEE-
