> 2rox
--EEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SBS-EEEEEEESBTB--EEEEEEEEETTEEEEEEEEE-------EEEEEEETTTTEE--S-EEEEEEE-TTSSEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEE--SS--EEEEEEEEETTEEEEEEEEE--
