> 2try
---SSS-TT-SEEEEEEETTTTEE-TT-EEEEEEE-TTSSEEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHTTT---SEEEEEEEEEESBTB--EEEEEEEEETTEEEEEEEEE--------SSSSTT-SEEEEEEETTTTEE-TT-EEEEEEE-TTS-EEEEEEEE--TTSEE--S--TTT--SEEEEEEE-HHHHHHHTT---SBS-EEEEEEE-SS---EEEEEEEEETTEEEEEEEEE----
