> 4lve
---EEEE-SEEEE-TTS-EEEEEEESS--EETTTTEE-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSSPEE---EEEEE------EEEE-SEEEE-TTS-EEEEEEESS--EETTTTEE-EEEEEE-TTS--EEEEETTTEEPTT--TTEEEEEETTEEEEEESS--GGG-EEEEEEE-SSSSPEE---EEEEE-
